name: doc
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ./main
      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          architecture: 'x64'
      - name: Install psychopy dependencies
        run: |
          sudo apt install libusb-1.0-0-dev portaudio19-dev libasound2-dev libsdl2-2.0-0
          curl https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.1-cp39-cp39-linux_x86_64.whl -o wxPython-4.2.1-cp39-cp39-linux_x86_64.whl
          python -m pip install --progress-bar off --upgrade pip setuptools wheel
          python -m pip install wxPython-4.2.1-cp39-cp39-linux_x86_64.whl
      - name: Install package
        run: python -m pip install --progress-bar off main/.[doc]
      - name: Display system information
        run: meg_info-sys_info --developer
      - name: Build doc
        run: sphinx-build ./main/doc ./doc-build/dev -W --keep-going
      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: doc-dev
          path: ./doc-build/dev

  deploy:
    if: github.event_name == 'push'
    needs: build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Download documentation
        uses: actions/download-artifact@v3
        with:
          name: doc-dev
          path: ./doc-dev
      - name: Deploy dev documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc-dev
          destination_dir: ./dev
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
